### ISSUE TITLE
STICKERZ!

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code#10]
we found that it's almost a crime that we don't have stickers yet and for the sake of our laptops we want to change that. @alicetragedy suggested taking the stamp we use for the certificates and play around with that one. We can also design more than one and have several stickers. Maybe one year-specific sticker and one general? or two? or three? :D

![stamp_red_small](https://cloud.githubusercontent.com/assets/1711357/6077590/caa77dea-adf0-11e4-9b88-79c4cba79f17.png)

@apertoclaudi any ideas on that? like where to put the year in on this ^ one? or maybe restructure it completely? all the feedback and ideas and drafts welcome <3

**Comment by alicetragedy** [comment]
ALL THE STICKERS <3

**Comment by ApertoClaudi** [comment]
i really like that sticker above (although the font "summer …" isn't centered … http://gph.is/118XqcL … too much quality assurance at work lately … sorryyyyy).
an inverted version would also be nice, copletely red with a white heart …
maybe a heartshaped sticker just with the hashtag for summer of code … 
i think about that and make some suggestions. :)

**Comment by anikalindtner** [comment]
argh! now i can't unsee it! #center

**Comment by ApertoClaudi** [comment]
hihi ^^

**Comment by alicetragedy** [comment]
sorry you are totally right, it's not centered :p I'll make sure to fix that for future use! 
I like your ideas for the stickers so far, I haven't really given it much thought this week yet.

**Comment by sareg0** [comment]
As mentioned on the call, I am happy to be a messenger person on the stickers if need to be handed over somehow for concat(). 

How do you think they would look best; white background with the writing on top, or clear background.
Upfront.ug had some totally sweet stickers with a clear background.

**Comment by alicetragedy** [comment]
@sareg0 that would be awesome, but I can also get someone to bring them to concat(), that would be no problem at all. (they'd be arriving on Friday night in Salzburg from Vienna).
I'd like to get a small edition of them done just for concat()/women techmakers with this design (since it's already done, I just have to center the text properly). I was thinking of the clear background too, but I think that, since the lines are so thin, white background might be a better choice! we could try getting matte ones though, I quite like them.

**Comment by sareg0** [comment]
True, I guess it helps if the lines are darker. ah well, all good!

**Comment by alicetragedy** [comment]
Since the stickerz have been successfully printed, I'm closing this issue and moving all conversations about the stickerz (like maybe another edition, or the ones for next year, or any other suggestions by @anikalindtner & @ApertoClaudi ) to the design repo. w00t!

**Comment by mrfoto** [comment]
I WANT THIZ STICKER NAO! :gift_heart:

**Comment by carpodaster** [comment]
giiief stickrz!

Am Fri Mar 13, 2015 at 12:3430AM -0700 schrieb Miha Rekar:
> I WANT THIZ STICKER NAO! :gift_heart:
>

**Comment by sareg0** [comment]
I am bringing some back to berlin :)

**Comment by alicetragedy** [comment]
@mrfoto I'm sure it can be arranged! :heart:

**Comment by mrfoto** [comment]
:shipit:

**Comment by sareg0** [comment]
I haz the stickerz! @mrfoto and @carpodaster you can hit me up for some.
