### ISSUE TITLE
RSVP for Day Off / Boat Party

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#130]
HitFox and SoundCloud are throwing us a "Day Off" party.. and it's going to be on a boat! :boat: :ship: 
## IMPORTANT: LOCATION CHANGE

There has been a last minute change to the location. The new location is not quite as well connected, but still reachable by public transport 

The new address is:

**Scharfe Lanke 109 -131
13595 Berlin**
https://goo.gl/maps/xq5Zu

There is the bus stop, located 10-15 min away walking: 
Gatower Str./Weinmeisterhornweg
Bus 134, N34 and X34

That connects nicely with the S-Bahn stop:
S Heerstr. (Berlin)  
S5, S75

Luckily It has a pretty high frequency, every 10 min.

Please confirm that you understand there is a new location by updating your comment with the following: 

**NEW LOCATION ACKNOWLEDGED**

Everyone on this list will be pinged directly, but if you can spread the word to people just in case it would be appreciated.

**Date**: August 27th
**Time**: 15:00 - 21:00

Drinks and food will be provided. A BBQ will be prepared on board around 17:00 and I will make sure there will be veggie and vegan options :)

Hopefully we'll have nice, sunny weather. There is the opportunity to go swimming, so bring swimwear and towel!

RSVPS ARE NOW CLOSED, AND CATERING ORDERS PLACED

There will of course be non-alcoholic drinks available on the day.

**Comment by nynnejc** [comment]
I'm in!
saw the change of location :)

**Comment by WlFranzi** [comment]
same here !!

**Comment by sareg0** [comment]
I will be going

**Comment by zaziemo** [comment]
Yeah, I'm also coming!

**Comment by Realtin** [comment]
I'm in too! 🚢

**Comment by finnp** [comment]
Me too :boat:

**Comment by 1000miles** [comment]
noice, i'm in! thx. :palm_tree:

**Comment by raluka** [comment]
me too! :boat: 

NEW LOCATION ACKNOWLEDGED

**Comment by hagenburger** [comment]
I’m in, thanks!

NEW LOCATION ACKNOWLEDGED

**Comment by anomiseditrix** [comment]
yay! i'm in!

re: dietary stuff... i'm allergic to peanuts in all forms, chickpeas, and soy protein (soy sauce and oil are ok, but tofu, soy flour or soy milk are a NG). thanks!

**Comment by sferik** [comment]
In. :tada:

**Comment by starkcoffee** [comment]
yeh! :boat:

**Comment by berlintam** [comment]
wooooot! :boat: :bell: 

ps - I'm a vegetarian

oops I misread (aka did not read) the instructions:
NEW LOCATION ACKNOWLEDGED

**Comment by lauralindal** [comment]
i wanna come, too ;) (but i understand that im not part of the priority-group & thats okay - ill come if there is room left :) )

**Comment by sareg0** [comment]
hey @lauralindal I am pretty sure there is space though, so consider yourself 'fest' :)

**Comment by lauralindal** [comment]
@sareg0 <3

**Comment by sareg0** [comment]
hey everyone. Can you please let us know in your comments if you have any special food needs/preferences? Thank you!

**Comment by ninabreznik** [comment]
Hey, I would also like to join the boat party and meet new SoC girls :)

**Comment by busyxin** [comment]
:+1: 
We still have some spots left, SoC students from previous years are also welcome, but please confirm before tomorrow (Tuesday) at noon. Thanks!

**Comment by katrin-k** [comment]
in

**Comment by lauralindal** [comment]
hey @sareg0, id prefer vegetarian food :)

**Comment by sarahkami** [comment]
I would like to join, if it's ok :)
Vegetarian food for me

**Comment by sareg0** [comment]
hey everyone, the order has already been placed for food, so no more RSVPs are being taken for that. If you want to let us know that you are going to come, but don't need food, please continue to let us know about your attendance. Otherwise, see you tomorrow!

**Comment by sareg0** [comment]
@nynnejc @WlFranzi @zaziemo @Realtin @finnp @1000miles @raluka @hagenburger @anomiseditrix @sferik @starkcoffee @berlintam @lauralindal @ninabreznik @katrin-k @sarahkami 

 The location for the boat party has changed. You can see the updated address in the issue description.

If you could update your comments to acknowledge the address change that would be great! That way we know everyone is informed :)

**Comment by berlintam** [comment]
ACKNOWLEDGED!

**Comment by sarahkami** [comment]
👍😊

**Comment by katrin-k** [comment]
got it :). thanks!

**Comment by zaziemo** [comment]
Seen!

**Comment by Realtin** [comment]
ok!

**Comment by nynnejc** [comment]
cool

**Comment by 1000miles** [comment]
acknowledged! thanks, @sareg0

**Comment by 1000miles** [comment]
on behalf of @lauralindal : acknowledged! :)

**Comment by anomiseditrix** [comment]
Got it! See you all tomorrow!

**Comment by katrin-k** [comment]
@sareg0 and me plan to go to the boat station by s-bahn & bike. we'll take the s5 from alexanderplatz at 13:51 (hopefully) and will bike from heerstr (~15-20 minute ride). you're welcome to join :). 
meeting place at alexanderplatz is the middle entrance hallway beside the s-bahn info center at, say, 13:40.

**Comment by finnp** [comment]
ACK

**Comment by anomiseditrix** [comment]
@sareg0 @katrin-k Can I meet you two at Heerstr. and ride over to the boat station with you? I'm coming on sbahn from Zoologischer Garten so I could just get off at Heerstr. and rendez-vous with you there? My number is 017684402084 just in case we need to get in touch!

**Comment by sareg0** [comment]
@anomiseditrix absolutely! I'll call when we arrive if we don't spot you

**Comment by anomiseditrix** [comment]
@sareg0 @katrin-k  Great! I'll aim to take the 14:05 s5 from Zoo, so I might be on the same
train as you!

**Comment by sferik** [comment]
It looks like a rain storm is coming. Is there anything we should do or bring in case it starts to :umbrella:?

<img width="555" alt="screen shot 2015-08-27 at 1 45 37 pm" src="https://cloud.githubusercontent.com/assets/10308/9519778/00198c64-4cc2-11e5-99ad-7959a28d0f00.png">

**Comment by sareg0** [comment]
Look for the "Fuchsbau" boat

**Comment by anomiseditrix** [comment]
Thanks everyone for a fantastic afternoon and evening! Had a wonderful time!

**Comment by sareg0** [comment]
seconded! Thanks @busyxin for all your orga work. And of course, HitFox and Soundcloud for sponsoring and making it possible :)

**Comment by busyxin** [comment]
Thanks everyone for attending and hope you all had a great time on board! Thanks @sareg0 for coordinating the guests. I hope we can repeat this next year ^^

Btw, we found another lonely towel looking for its owner, anyone missing a striped towel?

**Comment by anomiseditrix** [comment]
@busyxin if it's the multicoloured thinly striped one then it's the one i messaged you about last night!

**Comment by busyxin** [comment]
@anomiseditrix there are actually 2 towels, yours and the other one which is also multicoloured and striped.

One is rather beige and the other blueish, which one is yours?

**Comment by anomiseditrix** [comment]
mine is red and black and yellow and all colours with thin stripes?

**Comment by busyxin** [comment]
ok, yep got that one, I think in the dark I thought the yellow was beige. :)

**Comment by anomiseditrix** [comment]
lol... Thanks! :)

**Comment by 1000miles** [comment]
hey, thank you so much for the funny boat party yesterday. we had a great time talking to a lot of you and new people we didn't know yet.

best wishes,
thuy (and on behalf of @raluka)
