### ISSUE TITLE
RGSoC Wrap Up in Berlin 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code#138]
We want to wrap this year's Rails Girls Summer of Code program up with all of you wonderful people. 
:purple_heart: :yellow_heart: :green_heart: :heart:  Some teams will present their projects again and share their summer with us, and we want to say thank you to our wonderful sponsors (e.g. amazing SoundCloud) with this. There will be healthy snacks as well as assorted drinks and a wide range of alcohol-free drinks.

Details: 

**When:** 25th September, 7pm 
**Where:** SoundCloud Office, Rheinsberger Str. 76/77, 10115 Berlin, Germany
### This event is organized under the [Berlin Code of Conduct](http://berlincodeofconduct.org/), please read this carefully and only attend if you agree and abide by this. We will enforce the CoC.

RSVP with a comment if you want to come. :sparkles:

**Comment by alicetragedy** [comment]
I'll be there! :tada: :confetti_ball: :space_invader: :sparkles: :two_hearts:

**Comment by anikalindtner** [comment]
Me too! :sparkles: :dancers: :sparkling_heart:

**Comment by neonichu** [comment]
Me too! :dancer: :star2: :dizzy:

**Comment by sareg0** [comment]
I'll be there with bells on

**Comment by Lieke22** [comment]
I'll be there! (In Berlin that week :dancer: )

**Comment by ShellyCoen** [comment]
Jealous! Have fun everyone <3

**Comment by Realtin** [comment]
I'll be there with a +1

**Comment by janl** [comment]
I won’t be there, but you should all come to the big JSConf EU party at Radialsystem after the RGSoC Wrap Up, we start at 21:00 and it’s going to go for a while :)

**Comment by anikalindtner** [comment]
@janl \o/ will do! Count me in.

**Comment by zaziemo** [comment]
I'll come as well, but probably a little bit later.

**Comment by Realtin** [comment]
@janl yeeeees! I'll be there!

**Comment by 1000miles** [comment]
i am in, too. thanks! :)

**Comment by aberracja** [comment]
I'll be there!

**Comment by viddity** [comment]
I'll be there! <3

**Comment by raluka** [comment]
me too! :tada:

**Comment by siemieniec** [comment]
I'll be there too.

**Comment by starkcoffee** [comment]
lovely invite @anikalindtner. i'll be there of course!

**Comment by ariaru** [comment]
Me, too :)

**Comment by alhewpl** [comment]
I'll be there too. +1

**Comment by kaeff** [comment]
Hamburg represents! :ship: :hamburger:

**Comment by Malwine** [comment]
I am on board. :computer:  :gem: :heart:  :boom:

**Comment by eljojo** [comment]
bis dann!

**Comment by flaki** [comment]
🎇🎆 yay me to! 🎉😻

**Comment by ctrlaltjustine** [comment]
Since I'll actually be in Berlin, **COUNT ME IN!** :two_hearts:

**Comment by lislis** [comment]
\o/ I'll be there!

**Comment by rachelmyers** [comment]
I'd love to come! :ok_woman:

**Comment by WlFranzi** [comment]
cool

**Comment by Byron** [comment]
@kaeff Me to !

**Comment by afknapping** [comment]
Will be there!

**Comment by embrilliant** [comment]
Who can join this event? I'd like to come.

**Comment by sareg0** [comment]
Hi @embrilliant we'd love to have you there! Anyone should join who is interested in hearing about the experiences of the RGSoC participants for this year, and celebrating their work over the last 3 months. Can't wait to see you there :)

**Comment by bastilian** [comment]
I'll be there!

**Comment by froilainhaeckse** [comment]
I'm in

**Comment by svenfuchs** [comment]
:+1:

**Comment by sarahkami** [comment]
I'm in ⭐️

**Comment by thatbettina** [comment]
Me too!

**Comment by chastell** [comment]
Just booked a certain train arriving 20:06 at Ostbahnhof, so if you’ll still have me ~8:30 pm I’m more than happy to join. :sparkling_heart:

**Comment by anikalindtner** [comment]
yesssss of course @chastell! awesome awesome sauce :fireworks:

**Comment by alicetragedy** [comment]
@chastell it will not be a real party until you get there <3

**Comment by FloorD** [comment]
I'm in. :tulip:

**Comment by chastell** [comment]
> it will not be a real party until you get there

Were… were the RubyConf PT karaoke videos leaked already? :scream: 

> I'm in. :tulip:

:tada:

**Comment by hagenburger** [comment]
I will try to join for an hour or two between Reject.JS and their party. See you! :)

**Comment by anikalindtner** [comment]
@hagenburger but reject.js is on thursday, the 24th, no?

**Comment by hagenburger** [comment]
@anikalindtner hmm, right. I think I messed up my calendar a bit while changing time zones ;)

**Comment by jbspeakr** [comment]
Me +2

**Comment by johnjohndoe** [comment]
+2

**Comment by lucaong** [comment]
I'm in :)

**Comment by indirect** [comment]
I will come!

**Comment by BriocheBerlin** [comment]
I'll be there!

**Comment by zaziemo** [comment]
I'd also like to bring one person, please.

**Comment by plexus** [comment]
I'm coming as well :sparkles: :space_invader: :ghost: :bamboo: :sparkles:

**Comment by sxosxo** [comment]
I'm in.

**Comment by miveronese** [comment]
I'm in :)

**Comment by zzak** [comment]
Ok!

**Comment by sareg0** [comment]
good on ya' @zzak

**Comment by lucaspinto** [comment]
I should be there.

**Comment by madziaf** [comment]
I'll be there!

**Comment by fannivuniconnu** [comment]
I'll be there too!

**Comment by aakritigupta** [comment]
I'll be there too! :D

**Comment by flyjwayur** [comment]
I'll be there :D

**Comment by anomiseditrix** [comment]
see you tonight! :dancer:

**Comment by solnic** [comment]
"Piotr S. Conspiracy" is coming to RGSoC Wrap Up /cc @chastell :joy:

**Comment by sareg0** [comment]
so many amazing people in attendance!

**Comment by pxlpnk** [comment]
joining too (:

**Comment by necccc** [comment]
I'll be there :)

**Comment by nickgrace** [comment]
Please RSVP me. :)

**Comment by jgunawan** [comment]
I would like to rsvp, too. Thanks!

**Comment by hubudibu** [comment]
yay me too 🎉😺💫

**Comment by sareg0** [comment]
okey dokey, this is all closed up :) Thanks for coming everyone!!
