### ISSUE TITLE
add "how to find a coaching company" to student's guide

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code#17]
this is still missing as far as i can see. some hints and info about the process would be important to point out to students.

**Comment by alicetragedy** [comment]
:+1:

**Comment by alicetragedy** [comment]
If we are dropping advertising the coaching company idea too much, should we even do this, or can this issue be closed?

**Comment by anikalindtner** [comment]
yes!

CLOSE ALL THE THINGS

![tanzhund](https://cloud.githubusercontent.com/assets/1711357/6583090/23e93166-c762-11e4-80b0-9c51f2127b96.gif)
