### ISSUE TITLE
Update timeline

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#171]
It's a new season! \o/
We should probably update the timeline on the website soon, as we approach the end of the year and we start putting things in motion for next year.

**Comment by alicetragedy** [comment]
done in 088d9f603676f032174bb7cfbfae0ab2f275cc7d

**Comment by anikalindtner** [comment]
ah sorry, totally did not see this issue!

**Comment by anikalindtner** [comment]
#YOLOMERGED ALL THE THINGS

**Comment by alicetragedy** [comment]
😀😀😀
