### ISSUE TITLE
Adding categories or tags to the blog

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#174]
Since our blog is starting to grow quite a bit, I'd love to divide the posts into categories or add tags to them. For example, a category to see all the blog posts written by students (`student-posts`), one for conference-related stuff (`conferences`) and another for our `tips-and-tricks` or `success-stories`. This came to mind when browsing through (outdated) links on the Travis Foundation website. This would give outside people a possibility to directly link to stories of interest. 
I think this is definitely not a priority, but think it would be cool to look into it. Happy to take over this and pair with someone if needed! :tada:

**Comment by carpodaster** [comment]
Very cool! :+1:

**Comment by alicetragedy** [comment]
done in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/206. closing!
