### ISSUE TITLE
navigation glitch on mobile

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#175]
When viewing the website on mobile and clicking on the burger icon, the navigation list appears, but it's not possible to scroll all the way to the bottom of the navigation. 
Furthermore, from there there is no possibility to close the menu/get back to the home page — this should be changed to 1) either allow for the top bar to be shown at all times (so clicking on the logo takes you back to the homepage) or 2) add a menu point for the home page in the navigation list itself.

This should probably get fixed asap because it hinders proper usage on mobile devices. If you want to look into it, feel free to assign yourself to this issue/post a comment, otherwise I will be looking into it eventually. :)

**Comment by claucece** [comment]
Looks like the issue is due to the fact that 'overflow-x' is hidden on mobile. I think that option 2 is the best because it allows to be consistent with a mobile design. I can work on that.

**Comment by alicetragedy** [comment]
hey @claucece, did you get a chance to look at this?

**Comment by claucece** [comment]
Yes! I fixed the scrolling.. but while adding the home page to the menu I found another issue, seems like the size of the menu does not change accordingly. I can make a commit with the scrolling fixed and keep looking at the new issue.

**Comment by alicetragedy** [comment]
hey @claucece, I'd love to have the scrolling fix pushed when you can — at least then the menu would be working halfway properly, until you get a fix in with the size of the menu changing. does that work for you? Would be awesome!

**Comment by claucece** [comment]
Great! Not sure how to make the request.. should I follow this guide: https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/CONTRIBUTING.md?

**Comment by alicetragedy** [comment]
@claucece yes, that's the way to do it — create a new feature branch, commit your changes to it, push to your fork, and then make a PR against `gh-pages`, which is the branch we "deploy" on. Let me know if you're having any trouble!

**Comment by alicetragedy** [comment]
hey @claucece, would you still have time to look over and fix this issue over the next week? Please let me know by Friday (September 30th, 12:00 UTC) if not, so that I can hand this over to someone else to look at.

**Comment by mkalininait** [comment]
Can we close this issue @alicetragedy ?

**Comment by alicetragedy** [comment]
fixed in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/313
