### ISSUE TITLE
make use of heading hierarchy more consistent

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#179]
Right now, it seems like the headings we use in different pages throughout the site are slightly inconsistent, especially when looking at the sidebar headings and comparing them to single pages (Roles, Guides, etc..) and to the campaign-related pages (eg. sponsors).
Since the defaults in `variables.scss` seem pretty sensible, I believe our problem is in how we use the headings throughout the site :) I'd like to look at every single page and make sure we use the correct heading everywhere, so it stays consistent.

**Comment by troubalex** [comment]
I started looking at the different pages, and there are a number of inconsistencies. Some headlines use all caps, others don't, and there are differences regarding whitespace above and below the headlines.

Do we want all pages to use the same kind of headline styles? Or is there some kind of other system at work, that I don't see? 😄 

Also, there is only a sidebar on the blog, is that correct?

**Comment by alicetragedy** [comment]
hey @troubalex, thanks for looking into it! To answer all your questions:
- I think we'd like all pages to use the same kind of headline styles — except for the sponsor page, where I think the all caps work quite well in combination with the heading being red (unless you think otherwise?). There is otherwise no other system at work ;)
- the sidebar has been removed from all pages, and it's only on the blog now — I think we might keep it there for now, until we make bigger changes (we are thinking of doing a redesign sometime this year). 
- regarding the whitespace, I would seriously LOVE to have that fixed. it's all over the place. I think the titles definitely need more space, at least at the top..

**Comment by troubalex** [comment]
I actually thought about moving the all caps style over to all the other pages, because I think it makes for a nice separation between H1s and H2s.

Alternatively, we could make the difference in font sizes bigger.

Anyway, I'll play around with that, and post some screenshots along the way. 📷

**Comment by alicetragedy** [comment]
yes please! I also quite like it, and I'd be happy about changes :) 
thanks again! 👯
