### ISSUE TITLE
Landing Page Copy

### ISSUE THREAD

**Issue by sareg0** [rails-girls-summer-of-code/summer-of-code#18]
This is an issue for the landing page copy, and only copy (not related to the design), to keep the two discussions compartmentalised.

Just reduces clutter on the design discussions, but easily referenced when needed.

I'm just getting the discussion going, and perhaps we can sign off on copy, even while the design is being finalized. It may also help Claudi with her mockups to know the decided copy. 

Our target audiences are limited to the following, so I figure the content should be focused purely on them (in no particular order);
- Students
- Sponsors/Donors
- Coaches
- Mentors

If you feel that that list does not reflect the appropriate people coming to the landing (e.g. do we want to also have a focus on grabbing the attention of coaching companies), please say.

HERO IMAGE

------

TEXT UNDER HERO IMAGE
- It seems very to the point and clear

------

TILES
(Left to right)
**Tile 1**
- Title: Submit an Application
- Blurb: take a look at our applicant guide for everything you need to know

**Tile 2**
- Title: Submit your project
- Blurb:  Learn more about proposing or mentoring an open source project

**Tile 3**
- Title: Coach a Team
- Blurb: User your coding powers for good, and coach a team in the summer of code

**Tile 4**
- Title: Become a sponsor
- Blurb: take a look at our packages and perks

------

TIMELINE | HELPOUT
http://railsgirlssummerofcode.org/about/

------

SPONSORS

------

Go for it! Suggestions, likes, dislikes etc.

**Comment by anikalindtner** [comment]
great! I'd try to make it as short as possible. (If we need longer texts to make it look prettier, @apertoclaudi should give a shout)

TILES
(Left to right)
Tile 1

Title: Submit an Application
Blurb: take a look at our Application Guide (on how to become a student)*
Tile 2
*the text in the breakes could even be left out

Title: Submit your project
Blurb: Learn more about mentoring an Open Source project
Tile 3

Title: Coach a Team
Blurb: Help us with your experience and see how to become a coach
Tile 4

Title: Become a sponsor
- Blurb: take a look at our packages and perks

**Comment by lislis** [comment]
@sareg0 @anikalindtner can you maybe also include where links should point to? Would make things much easier for me :)

**Comment by ApertoClaudi** [comment]
Blurb? :D Funny description!

I'll see, if I have time in the evening, then you get a layout update with all your texts.

**Comment by lislis** [comment]
@ApertoClaudi no worries! this is mostly for me. I can handle the design having cupcake ipsum and putting the right texts into the code

**Comment by anikalindtner** [comment]
will do later tonight/tomorrow. if someone has time before, go for it!

**Comment by ApertoClaudi** [comment]
@lislis  Well, I changed my cupcake ipsum allready. But from now on I ignore the new textinput. ;)

**Comment by anikalindtner** [comment]
@lislis
+ more about us: to http://railsgirlssummerofcode.org/about/
+ submit an application : to http://railsgirlssummerofcode.org/students/application/
+ coach a team: to http://railsgirlssummerofcode.org/guide/coaching/
+ become a sponsor: to http://railsgirlssummerofcode.org/sponsors/packages/
+ same goes for the sponsor teaser "the right place to be" ^

**Comment by anikalindtner** [comment]
@ApertoClaudi btw. I couldn't believe it myself, but"blurb" seems to be an actual word. I only learned that while working for RGSoC as well. hehe. such a nice one, that sounds like a sound ;D

![screen shot 2015-02-25 at 23 11 50](https://cloud.githubusercontent.com/assets/1711357/6381721/b8f7ee92-bd43-11e4-90a2-ccd5149646a4.png)

**Comment by sareg0** [comment]
Jop! It IS a real word... But I do have tendency to make these things up :)

**Comment by ApertoClaudi** [comment]
@anikalindtner Okay… that's new to me, but funny anyway! I knew it by the name "copy" or "abstract".

**Comment by sareg0** [comment]
True, those are nice words. Blurb is usually on the back of a book. It's not an abstract of the book, but a brief explanation, or setting of the stag for the books premise :)

**Comment by anikalindtner** [comment]
@ApertoClaudi hahahahahaha

**Comment by alicetragedy** [comment]
@lislis some (reaaaaally) minor things I noticed today that might need changing:

**Top menu**
- remove FAQs link

**Main text**
- replace "from July-September" to "from July to September"

**Boxes**
- "Coach a team" instead of "Coach a Team"
- "Submit your application" instead of "Submit an Application"

**Timeline**
- I'd remove the . after the months eg. "02.02" instead of "02.02." (not to be pedantic but I think that the period after the month is only needed if the year comes after, and it looks better without since there's the colon coming right after)

thank you <3

**Comment by anikalindtner** [comment]
I also have a change for the copy. Basically I was trying to make the main text less, so that it doesn't use up too much space.

![screen shot 2015-02-27 at 19 53 34](https://cloud.githubusercontent.com/assets/1711357/6419069/80303006-beba-11e4-9df9-5c15ac80e5bc.png)
"With our fellowship program we aim to foster diverstiy in Open Source. Selected teams recieve a three-months scholarship to work on Open Source projects of their choice."

**Comment by sareg0** [comment]
How do we all feel about the progress of this issue, has all of your feedback been integrated.

I have maybe one small change.

"With our fellowship program we aim to foster diverstiy in Open Source. Selected teams receive a three-months scholarship to work on Open Source projects of their choice."

I feel like it implies people can select any open source project, which could be misleading. Perhaps we could suggest something like

"With our fellowship program we aim to foster diversity in Open Source. Selected teams receive a three-months scholarship to work on selected projects."

Or something along those lines

**Comment by sareg0** [comment]
I'm closing this issue cause it's big and we're moving the discussion to somewhere else
