### ISSUE TITLE
Remove FAQ Sections

### ISSUE THREAD

**Issue by sareg0** [rails-girls-summer-of-code/summer-of-code#19]
The decision has been made to to scrap the FAQ, as it is merely duplicate info.

1) http://railsgirlssummerofcode.org/faq/
needs to be consolidate with http://railsgirlssummerofcode.org/about/

2) http://railsgirlssummerofcode.org/faq/sponsors/
needs to be consolidate with http://railsgirlssummerofcode.org/about/sponsorship-guidelines/

3) http://railsgirlssummerofcode.org/faq/students/
needs to be consolidate with http://railsgirlssummerofcode.org/students/application/

I am assessing if there is anything in the FAQ sections that is NOT addressed in the corresponding guide. I will post the Sections here for posterity, and double checking, but am going to remove them now.

1. FAQ: Sponsors
-------------

**What is Rails Girls Summer of Code (RGSoC)?**
**Is it a global initiative?**
**Who is running this?**
**Who can participate as a student?**
**Where will RGSoC take place?**
**I have more questions!**

**What is Rails Girls Summer of Code?**

Rails Girls Summer of Code (RGSoC) helps Rails Girls students (and students from other, comparable initiatives) get into Open Source.

Just like in Google Summer of Code and Ruby Summer of Code, students will be paid so they’re free to work on Open Source projects for a few months. Unlike those programs, the Rails Girls Summer of Code is about helping students to further expand their knowledge and skills by contributing to a great Open Source project (rather than producing highly sophisticated code).

**Is it a global initiative?**

Yes! Rails Girls Summer of Code is happening worldwide and students from all over the world are welcome to apply.

**Who is running this?**

The initiative is a community-driven one, so RGSoC is run by volunteers all over the world. Amazing people helping as organizers, coaches, mentors, supervisors are making this happen. You can too: Send an email to summer-of-code@railsgirls.com and join the international team!

**Who can participate as a student?**

We’re looking for women who have participated in any Rails Girls, RailsBridge, or similar newcomer workshop, have participate in a Ruby/Rails study group, or otherwise are getting started with Ruby/Rails as newcomers.

Unlike Google Summer of Code, no status as a student at a university is necessary, and there are certainly no degree or age limitations.

This initiative is focused on bringing more women into the world of open source. Men are not excluded however women are given priority.

**Where will Rails Girls Summer of Code take place?**

Since Rails Girls Summer of Code is an international initiative, there is no one “place” where everything happens. It depends on where students live and want to work

We will try to help find coaches as near as possible to a students location to avoid the student having to accomodate herself in a different city. Ideally coaches can provide a desk at their own workplace so students can sit next to them, ask questions and get support.

**I have more questions!**

Find the contact details here: Contact.

______________

PS it's not a typo, the general FAQs section title was indeed called 'FAQ: Sponsors'

2. FAQ: Sponsors
--------------------------

**What about VAT and tax deduction for my donations?**
**What happens if you don’t reach your goal or RGSoC gets cancelled?**
**What happens to any left-over budget from the 2014 Summer of Code?**

**What about VAT and tax deduction for my donations?**

We don’t really know about tax laws everywhere in the world but according to our tax advisor: “Contributions and payments to Rails Girls Summer of Code are not deductible as charitable contributions for federal income tax purposes. However, they may be deductible under other provisions of the Internal Revenue Code (for US) or your local tax authority’s advice.”

A word about VAT. Sorry to bother you - we’ll keep a long story short. If you’re not from Europe (to be precise - from the EU) you can skip this. For all the others: we have to struggle with the odd EU VAT regulations for the above mentioned packages. While you fill out the form and entered an EU country we will show a field to ask for your VAT ID. If you have one please enter it - otherwise your contribution will be reduced by 19% VAT. You come from Germany? We will show you a field to ask if VAT is a recoverable tax for you. If so, we will add the 19% VAT to your contribution and ask you to complete your address data.

**What happens if you don’t reach your goal or RGSoC gets cancelled?**

If for some reason the Summer of Code can’t go ahead as planned, donors will be offered a refund of their donation. Alternatively you can decide to have your donation go to the Rails Girls organization to share your donation with other, future Rails Girls events across the globe.

What happens to any left-over budget from the 2013 Summer of Code?

Any money left over from the campaign will be saved for next year’s Rails Girls Summer of Code. Should there be no Summer of Code in 2015, the Rails Girls organization will decide how to best spend any left over donation money on other non-profit initiatives.

3. FAQ: Students
---------------
**Who can participate as a student?**
**Where will RGSoC take place?**
**How much money will students receive?**
**Are students required to work full-time for all of the three months?**
**What if I don’t fit all the criteria stated on the student page?**
**How will you make sure that the students participate continuously in their projects?**
**What does an ideal project goal look like?**

**Who can participate as a student?**

We’re looking for women who have participated in any Rails Girls, RailsBridge, or similar newcomer workshop, have participate in a Ruby/Rails study group, or otherwise are getting started with Ruby/Rails as newcomers.

Unlike Google Summer of Code, no status as a student at a university is necessary, and there are certainly no degree or age limitations.

This initiative is focused on bringing more women into the world of open source. Men are not excluded however women are given priority.

**Where will Rails Girls Summer of Code take place?**

Planet earth.

Rails Girls Summer of Code is an international initiative. Thus, it does not matter where a student or coach lives or where a company is located.

Coaches are supposed to be located as near as possible to students to avoid the student having to accommodate herself in a different city. Ideally coaches can provide a desk at their own workplace so students can sit next to them, ask questions and get support.

**How much money will students receive?**

Up to 1500 USD per month, for a period of three months.

Are students required to work full-time for all of the three months?

In order to immerse themselves and make a significant contribution to an Open Source project, we recommend that they do. However, if you feel you could achieve these ends working on a more limited time-frame, please explain in your application how you will make things work regardless, and we will consider your points.

**What if I don’t fit all the criteria stated on the student page?**

The criteria are not minimal standards, but rather recommendations for what we consider to be important for successful participation in a project. That said, we will not necessarily exclude anybody from applying, we will instead give points to each criterion fulfilled. The higher your score, the higher your chance of being selected given that there will most likely be more applicants than places. If you do not fulfil any particular criterion as stated (e.g. coach and student in the same location), but have found a way around this, please explain that to us in your application. We will consider your points and if convinced, give you a point for the criterion anyway.

**How will you make sure that the students participate continuously in their projects?**

We will require some reporting on progress, most probably a combination of informal (e.g. blog posts about lessons learned) and more formal reporting.

**What does an ideal project goal look like?**

Please have a look at our application guide for an in-depth explanation of what a good project goal looks like.

**Comment by sareg0** [comment]
FAQ: Sponsors
-------------


What is Rails Girls Summer of Code (RGSoC)?
Is it a global initiative?
Who is running this?
Who can participate as a student?
Where will RGSoC take place?
I have more questions!
What is Rails Girls Summer of Code?

Rails Girls Summer of Code (RGSoC) helps Rails Girls students (and students from other, comparable initiatives) get into Open Source.

Just like in Google Summer of Code and Ruby Summer of Code, students will be paid so they’re free to work on Open Source projects for a few months. Unlike those programs, the Rails Girls Summer of Code is about helping students to further expand their knowledge and skills by contributing to a great Open Source project (rather than producing highly sophisticated code).

Is it a global initiative?

Yes! Rails Girls Summer of Code is happening worldwide and students from all over the world are welcome to apply.

Who is running this?

The initiative is a community-driven one, so RGSoC is run by volunteers all over the world. Amazing people helping as organizers, coaches, mentors, supervisors are making this happen. You can too: Send an email to summer-of-code@railsgirls.com and join the international team!

Who can participate as a student?

We’re looking for women who have participated in any Rails Girls, RailsBridge, or similar newcomer workshop, have participate in a Ruby/Rails study group, or otherwise are getting started with Ruby/Rails as newcomers.

Unlike Google Summer of Code, no status as a student at a university is necessary, and there are certainly no degree or age limitations.

This initiative is focused on bringing more women into the world of open source. Men are not excluded however women are given priority.

Where will Rails Girls Summer of Code take place?

Since Rails Girls Summer of Code is an international initiative, there is no one “place” where everything happens. It depends on where students live and want to work

We will try to help find coaches as near as possible to a students location to avoid the student having to accomodate herself in a different city. Ideally coaches can provide a desk at their own workplace so students can sit next to them, ask questions and get support.

I have more questions!

Find the contact details here: Contact.

**Comment by sareg0** [comment]
FAQ: Sponsors

**What about VAT and tax deduction for my donations?**
**What happens if you don’t reach your goal or RGSoC gets cancelled?**
**What happens to any left-over budget from the 2014 Summer of Code?**



**What about VAT and tax deduction for my donations?**

We don’t really know about tax laws everywhere in the world but according to our tax advisor: “Contributions and payments to Rails Girls Summer of Code are not deductible as charitable contributions for federal income tax purposes. However, they may be deductible under other provisions of the Internal Revenue Code (for US) or your local tax authority’s advice.”

A word about VAT. Sorry to bother you - we’ll keep a long story short. If you’re not from Europe (to be precise - from the EU) you can skip this. For all the others: we have to struggle with the odd EU VAT regulations for the above mentioned packages. While you fill out the form and entered an EU country we will show a field to ask for your VAT ID. If you have one please enter it - otherwise your contribution will be reduced by 19% VAT. You come from Germany? We will show you a field to ask if VAT is a recoverable tax for you. If so, we will add the 19% VAT to your contribution and ask you to complete your address data.

**What happens if you don’t reach your goal or RGSoC gets cancelled?**

If for some reason the Summer of Code can’t go ahead as planned, donors will be offered a refund of their donation. Alternatively you can decide to have your donation go to the Rails Girls organization to share your donation with other, future Rails Girls events across the globe.

What happens to any left-over budget from the 2013 Summer of Code?

Any money left over from the campaign will be saved for next year’s Rails Girls Summer of Code. Should there be no Summer of Code in 2015, the Rails Girls organization will decide how to best spend any left over donation money on other non-profit initiatives.

**Comment by alicetragedy** [comment]
I think the sponsor FAQs are actually the only ones that have information that is important and that we don't have anywhere else.. but not 100% sure :p

**Comment by sareg0** [comment]
okay, I put them all up into the top text. It's definitely not there @alicetragedy so we need to pack that in somewhere with Sponsorship guidelines I guess.

**Comment by anikalindtner** [comment]
\o/

**Comment by sareg0** [comment]
Okay, I have merged with pull request myself. 

Sorry for the lack of consultation. There is not changed info, just a tacking on of guidelines in addition to packages
https://github.com/rails-girls-summer-of-code/summer-of-code/pull/22

The content still needs to be reviewed, and have the information from the FAQs for sponsors somehow integrated.

**Comment by sareg0** [comment]
As mentioned above, we need to rewrite the sponsor FAQ content that we don't have in the 'sponsorship guidelines'

I'm going to just propose the change in this comment, and then if it looks OK, then will lodge a pull request to double check the changes before publish.

This is going to be added to the ['Sponsorship Guidelines'](http://railsgirlssummerofcode.org/sponsorship-guidelines/) page


------------------------

###Information on VAT and Tax Deductability

**For donors based in Germany:**
When filling out the donation form, we will show you a field to ask if VAT is a recoverable tax for you. If you answer 'yes', we will add the 19% VAT to your contribution.

**For donors based in other European Union country:**
If you enter an EU country into the 'Country' field of the donation form, you will be shown a field for your VAT ID number. If you have one please enter it - otherwise your contribution will be reduced by 19% VAT. 
e.g. If you donate $2500, and do NOT enter your VAT number, Rails Girls Summer of Code receives $2025 of your donation.

**For donors based elsewhere:**
We don’t really know about tax laws everywhere in the world but according to our tax advisor: “Contributions and payments to Rails Girls Summer of Code are not deductible as charitable contributions for federal income tax purposes. However, they may be deductible under other provisions of the Internal Revenue Code (for US) or your local tax authority’s advice.”

### Logistical Disasters 
If for some unforeseen reason the Rails Girls Summer of Code can’t go ahead as planned, donors will be offered a refund of their donation. Alternatively you can decide to have your donation go to the Rails Girls organization to share your donation with other, future Rails Girls events across the globe.

### Left over monies
Any money left over from the campaign will be saved for next year’s Rails Girls Summer of Code. Should there be no Summer of Code in 2015, the Rails Girls organization will decide how to best spend any left over donation money on other non-profit initiatives.


_________

**Comment by sareg0** [comment]
I'm gonna close this cause it's in the PR I just did :)

**Comment by alicetragedy** [comment]
you can go ahead and close this issue @sareg0 as soon as the pull request is mergeeddddddddd :tada:

**Comment by sareg0** [comment]
SUPERRRR!!!
