### ISSUE TITLE
Website markup is slightly broken

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/summer-of-code#193]
The Become-a-sponsor/Timeline/Help-out section markup is broken on most pages (e.g. CC guide, mentor guide etc).  
![screen shot 2016-03-11 at 14 37 40](https://cloud.githubusercontent.com/assets/1745735/13704576/e460b76a-e79c-11e5-9cec-4c39e98c13b8.png)

**Comment by alicetragedy** [comment]
fixed in https://github.com/rails-girls-summer-of-code/summer-of-code/commit/81231c9c484ccbfe8a721fca367b34f7d64007ab
