### ISSUE TITLE
Add mobile-friendly image to application guide

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#194]
the image is a little small on a mobile device, so Beccy has provided us with an image that is split differently to improve the mobile experience.

**Comment by alicetragedy** [comment]
this is the image -> ![2016-soc-guide-mob](https://cloud.githubusercontent.com/assets/3143348/17971594/c193a8f6-6adb-11e6-9045-2ecf62ace4ce.png)

**Comment by katrin-k** [comment]
Resolved using `<img srcset="…">`
This doesn't work on Android 4.x and Opera Mini, but is likely to be future-proof. Android 5x handles it.

**Comment by alicetragedy** [comment]
done in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/291 — thank you @katrin-k! <3
