### ISSUE TITLE
Press page

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#199]
It would be great to have a proper, nice-looking press page on the site. :)
@anasofiapinho is working on collecting press-related content, this will also help us to get a grip on our actual press material. As a first inspiration, she suggested the following: https://brandfolder.com/slack

In this issue, I'd also like to collect ideas of styles and a list of things to add to the press page in the future.

**Comment by anasofiapinho** [comment]
Update: We have been working on the press page and press kit on the issue [#128 from the organization repo](https://github.com/rails-girls-summer-of-code/organization/issues/128).

**Comment by anasofiapinho** [comment]
We have a new Press Page!
https://github.com/rails-girls-summer-of-code/summer-of-code/pull/214

**Comment by anasofiapinho** [comment]
Making new changes on the press page here
https://github.com/rails-girls-summer-of-code/summer-of-code/pull/263
