### ISSUE TITLE
Add Coaching Companies to the Hall of Fame

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/summer-of-code#200]

**Comment by alicetragedy** [comment]
could you add this as a point in the already existing issue https://github.com/rails-girls-summer-of-code/summer-of-code/issues/167 instead? that way we have a better overview when setting up the hall of fame :) thanks!!

**Comment by mkalininait** [comment]
Good point @alicetragedy, thank you! Closing this issue then.

**Comment by alicetragedy** [comment]
yay! :tada: and great that you pointed it out the other day, we don't really support CCs on the site enough and this definitely has to change.
