### ISSUE TITLE
timeline stars flicker when hovering on main page sections

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#215]
The right side ⭐ list elements of the timeline on the main index flicker (as in, disappear and then reappear) when hovering on the different landing-teasers. This seems to be triggered by a combination of the `transform` on the landing-teaser link hover and of the `display: inline-block` set on an element with `.fa` class (a font awesome default). 

Not sure what the best way to overwrite it is, but it probably shouldn't be overwritten at the top class level.

**Comment by claucece** [comment]
Weird behavior. Looks like it is due to the 'transform' property. But, when the screen is resized is gone. I'll dig in it further.

**Comment by alicetragedy** [comment]
great, thank you @claucece! 👍

**Comment by mkalininait** [comment]
Can't reproduce anymore. Should we close it?
