### ISSUE TITLE
Add coaching company list for 2016

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#220]
We have the sponsors listed on the website but don't have a list of the coaching companies, which is a pity given how much they invest in helping teams by providing space and more coaches. 

I'd like to create a page similar to the sponsor page, where we list all the coaching companies with their logo (and maybe their location and/or a blurb about the company).

**Comment by anasofiapinho** [comment]
I am going to add them here:
https://docs.google.com/spreadsheets/d/15TqkQI4y_wT5VRRUM4ZnCNUeuAu4jmiHysFWmw-U5OQ/edit?usp=sharing

**Comment by carpodaster** [comment]
@alicetragedy Does "coaching company" still fall under the definition of sponsor? I remember we talked about that two years ago because that would be unfair for sponsors who chip in real money.

That being said, I like the idea of listing coaching companies. :)

**Comment by anasofiapinho** [comment]
@alicetragedy I have added all the coaching companies I could find and linked it to the websites. When I saw some info about coworking spaces and university I added that as well. Maybe we could also talk with the supervisors to get the rest of the info. I was wondering if we could make a blog post about the working spaces of our students. I know it's not directly related to the coaching companies, but it is a way to talk about them without being too intrusive. If some of the students could take pictures it would be even better!

**Comment by alicetragedy** [comment]
awesome, great work @anasofiapinho. Thanks!
I think a blog post about the working spaces is a great idea, can you add this to the [blog post idea list](https://docs.google.com/spreadsheets/d/1Hz0WFG72o2GzYX9fytVKIhmIG1ITczcyUC2KfvFZWNw/edit#gid=830023321) in the spreadsheet? then we have an overview. If you'd like to write it/want to take ownership, feel free to add yourself to the blog editorial calendar or add your name in the blog post idea list :)

**Comment by alicetragedy** [comment]
done in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/234, closing this!
