### ISSUE TITLE
Berlin RGSoC Kick-Off-Picnic! Now: Indoor-Picnic at Travis CI GmbH 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code#226]
#### UPDATE:

**The weather goods don't seem to be with us and we will do the picnic tomorrow at Travis CI, Rigaer Str. 8 instead. We have a nice balkony and a courtyard, so if the ☀️  decides to join us, we can enjoy that as well.**
## 

We want to start this year's Rails Girls Summer of Code program up with all of you wonderful Berlin people. :purple_heart: :yellow_heart: :green_heart: :heart:  

This Picnic is sponsored by our friends at [Neighbourhoodie](https://neighbourhood.ie/)!
![screen shot 2016-06-29 at 12 07 19](https://cloud.githubusercontent.com/assets/1711357/16448509/2565eab8-3df2-11e6-88b8-c43d85c8fbfe.png)

**Details**: It's summer in Berlin, so let's meet for a nice picnic <strike>in the park</strike> inside! We will also provide some water and non-alcoholic drinks and ask you to stay on the _mostly_ alcohol-free side of drinks that you bring, thank you 🙇 .

**What:** A picnic - bring some food and we'll share all the things 
**When:** 8th of July 2016, 6pm CEST
**Where:** At Travis CI Gmbh, [Rigaer Str. 8](https://www.google.de/maps/place/Travis+CI+GmbH/@52.5178732,13.4535313,17z/data=!3m1!4b1!4m5!3m4!1s0x47a84e6700ca7771:0x8eebbb66a945d599!8m2!3d52.51787!4d13.45572?hl=en), near Frankfurter Tor/ Bersarinplatz! 

![screen shot 2016-07-07 at 10 01 07](https://cloud.githubusercontent.com/assets/1711357/16646320/c72187f8-4429-11e6-920b-13f5804d0334.png)
### This event is organized under the [Berlin Code of Conduct](http://berlincodeofconduct.org/), please read this carefully and only attend if you agree and abide by this. We will enforce the CoC.

**RSVP** with a comment if you want to come and **mention what you are planning to bring for noms** 🍔 🍞 🍌 🍅 🍏 🍤 🍉 🍗 🌽  🍒 🌰 🍍  :sparkles:

**Comment by siemieniec** [comment]
Woohoo! I will be there. Thanks!

**Comment by anikalindtner** [comment]
🙋  will be there and bring some bratwurst (~20) for bbq-ing!

**Comment by sareg0** [comment]
I will be there, but probably from 19:00 or 19:30
I will also bring a vegan snack such as dips 'n' veggies, or some such thing

**Comment by Karla-Isabel-Sandoval** [comment]
Would love  to join as well and to meet @sareg0 and @anikalindtner in person ! Bringing watermelon and zucchini.

**Comment by alicetragedy** [comment]
I'll be there as well! Will bring cherry tomatoes 🍅  and a cantaloupe 🍈 !

**Comment by lisbethmarianne** [comment]
It's my birthday. I'd love to celebrate with RGSoC. 🎈 

I'll bring some birthday cake. 🍰

**Comment by porras** [comment]
I'm in! I'll bring the Spanish version of Kartoffelsalat and Alkoholfrei Weißbier ☀️ 😎 🎈

**Comment by carpodaster** [comment]
I'll be there (with progeny 👶 ) from 18-19:30'ish – I'll bring a salad based on beans, apples and green onions. Sounds yucky but it's actually super-delicious. I promise!

**Comment by soff22** [comment]
Hello everybody,
I`m so happy I will be with you for the kick-off party this year. I am a student from the last year edition, **team RailsGEnthusiasts**. This year I will be supervisor of team XYZ from Prague.
See you next Friday :)

**Comment by hagenburger** [comment]
I’m happy to join :)

**Comment by langjoh** [comment]
Hallo, Team Joda aka Dayana & Johanna are happy to join as well. We will bring Fladenbrot, Halloumi and olives.

**Comment by hoffl** [comment]
Hi! I'll be joining, too, but I don't know yet what I'll bring. I'll think of something and note it here. :-)

**Comment by bitboxer** [comment]
Will also join you all 👍 
![](http://i.giphy.com/lcygVgIY9vhvy.gif)

**Comment by soff22** [comment]
I`m almost ready :) Finally I found a good place near Volkspark Friedrichshain to spend the nights in Berlin. I`ll bring some typical Bulgarian food and I think to prepare some healthy bites :)
See you on Friday guys :)

**Comment by remydagostino** [comment]
I'm in. Will bring some vegan snacks.

**Comment by joecorcoran** [comment]
I'll be there! ❤️

**Comment by jessicarose** [comment]
I'll be there, if that's ok?💖

**Comment by alicetragedy** [comment]
Yesssssss @jessicarose that's more than ok! 🙌

**Comment by bitboxer** [comment]
You are in town @jessicarose ? Awesome! See you on Friday 👍

**Comment by froilainhaeckse** [comment]
Will be there.

**Comment by bl00dymarie** [comment]
Hey, so I am planning to bake some lemon key muffins, not vegan but vegetarian :P 

Is anybody considering an alternative place to go in case of rain/bad weather? Seems this year we are heading directly from springtime to autumn :D 

( @soff22 I've read "you are a survivor of the XYZ team, just a supervisor that's great :) )

**Comment by soff22** [comment]
Thanks Marie :).
Hey guys, could you please somebody of you give me mobile number, because this is my first time in Berlin and I`m not sure where exactly to find you in the park, and just for any case.
Thank you.

**Comment by alicetragedy** [comment]
@lilaluca Hey Marie, yes we're working on an alternative location and @anikalindtner will post more info about it in the issue once this is settled. @soff22 unfortunately I have a foreign number, but I think there is a good number of people from Germany here who can send you a private message with their number. :)

**Comment by s-urbaniak** [comment]
Hello, I will be there too :-)

**Comment by anikalindtner** [comment]
UPDATE: We moved the picnic location because of ☔ . It's now at Travis CI GmbH, Rigaer Str. 8! See you tomorrow <3 

@siemieniec @sareg0 @Karla-Isabel-Sandoval @lisbethmarianne @porras @carpodaster @soff22 @hagenburger @Powerglove @hoffl @bitboxer @remydagostino @joecorcoran @jessicarose @theaamanda @lilaluca @s-urbaniak

**Comment by linberg** [comment]
I will bring Kartoffelsalat and some veggie spring rolls :)

**Comment by soff22** [comment]
According local weather forecast site, it shows occasional rainings for Berlin..., not sure, but anyway we should have a shelter. The place is even closer to the place where I`ll be staying :), so I will not be concerned about late evening party :)
See you tomorrow

**Comment by yoshuawuyts** [comment]
I'll probs swing by; choice of munchies will be inspired by the local grocery store selection 🍡

**Comment by ferbsx** [comment]
I'll try to be there with cake! 💃 🎉

**Comment by ariaru** [comment]
Me +2 if we'll make it (I hope we will), in which case we will also bring some food :)

**Comment by this-sandra** [comment]
Hello, I will try to be there and bring something vegan. :-)

**Comment by lisbethmarianne** [comment]
1 or 2 friends might join me.

**Comment by sarahkami** [comment]
I think about joining, and if so I bring something and maybe a +1 
(isn't that a defined cryptic message^^)

**Comment by alexhumphreys** [comment]
I'd like to join, I'll bring some bread and humus :)

**Comment by BriocheBerlin** [comment]
I'll be there, too. Bringing @1000miles and +1.
Ah, and food of course. Something from the turkish market.

**Comment by fidothe** [comment]
I'll be coming. Will try to bring some nice GF bread and things to put on it...

**Comment by ariaru** [comment]
My sister who is visiting isn't feeling :100: , so we are bailing out :(
Have fun everyone!

**Comment by anikalindtner** [comment]
thanks for the awesome time everyone! closing this now.
