### ISSUE TITLE
Link changes and leftover content

### ISSUE THREAD

**Issue by katrin-k** [rails-girls-summer-of-code/summer-of-code#25]
With the new landing page coming up, i also looked through all of the other pages and found some more stuff to change.

About page http://railsgirlssummerofcode.org/about/
- [x] remove Chat paragraph

What’s the policy on setting the sidebar?
- [x] Pages that don’t have it: team (no space left), sponsorship packages (space left), sponsors page (no space left), campaign (space left)

Sidebar
- [x] remove "Sponsorship Guidelines" item in About section
- [x] remove "Become a Sponsor" item in Get Involved section

Sidebar -> Timeline
- [x] adjust date writing according to new landing page
- [x] set space between stars and text

CoC http://railsgirlssummerofcode.org/about/code-of-conduct/
- [x] remove the Trust Committee from last year. 

Imprint http://railsgirlssummerofcode.org/about/imprint/
- [x] first Travis address is Prinzessinnenstr. -> change to Rigaer
- [x] remove link to contact page. Change "For other means to contact us, see here." to "For any other requests, please contact us by email." (with summer-of-code@… address)

Footer
- [x] change link "Sponsorship Guidelines" to "Sponsorship Packages & Guidelines" http://railsgirlssummerofcode.org/guide/sponsorship/

**Comment by lislis** [comment]
Thanks for looking at stuff like this!

**Comment by alicetragedy** [comment]
@katrin-k turned your list into a checkbox one, so we have an overview of what needs to be done. I'm happy to assign this issue to myself and make those changes if you have no time! (:

**Comment by alicetragedy** [comment]
re: sidebar - I didn't remove the links, I just changed the link to the sponsorship guidelines (it was broken) and left the become a sponsor item, as it's the spot in the sidebar you can get to that page from; but I can also remove it if needed! let me know :)

**Comment by katrin-k** [comment]
naa, i wouldn't say it needs to be removed. it was rather for making it consistent with the structure of the toggle navigation. and the topic of becoming a sponsor is also mentioned directly below.

**Comment by alicetragedy** [comment]
I think that you're totally right and that ideally it would make sense to keep the structure in the sidebar the same as the one in the new top menu.. Since the Sponsor heading is missing in the sidebar, we're left with some "loose" sponsor pages that need to be linked somewhere. Maybe it would make sense to add a sponsor menu point in the sidebar or to get more links in the "Become a sponsor" bit.

**Comment by alicetragedy** [comment]
ALL THE CHANGES HAVE BEEN MADE OMG.
issue can be closed!! :tada:
