### ISSUE TITLE
remove /js/ folder and default layout

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/summer-of-code#26]
I migrated most of the pages to use the (new) bootstrap layout.
That means we can use all the bootstrap grid classes to build layouts. yay!
I already deleted the `/css/` folder and put all things to `/assets/stylesheets` where we can use scss. amazing! 
The `legacy.scss` contains the old css file but is not included on the newer pages. I try to have separate scss files to make it easier to find things.
Next step is deleting `/js/`. I already have all scripts in `assets/javascripts/` but want to wait for a bit and see how it goes and if I broke something.
So far so good.

**Comment by sareg0** [comment]
OMG this is amazeballs. What's the status on this one now. Are you gonna remove the js folder.

**Comment by sareg0** [comment]
As we spoke in the call, @lislis will take a quick look at this, and see if she can get it closed up before her holiday. Many thanks Lisa :)

**Comment by alicetragedy** [comment]
:clap:
