### ISSUE TITLE
General improvements to the mobile experience

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#282]
There are lots of small glitches on the website which hinder the mobile experience, and I'd like to collect all of them here so we have a better overview.
- [x] mobile-friendly image for Application Guide (issue https://github.com/rails-girls-summer-of-code/summer-of-code/issues/194)
- [x] ⚠️ big issue with the navigation (issue https://github.com/rails-girls-summer-of-code/summer-of-code/issues/175 - PR #285)
- [x] megaphone in footer hides text on mobile (my suggested fix: remove it entirely on small displays)
- [x] sample weekly schedule in `students/todo/` is cut off (suggested fix: make image responsive/adapt to screen) (closed in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/284)
- [x] lots of scrolling on a lot of pages (suggested fix: e.g. remove the sponsor footer on smaller devices)
- [x] improve look of coaching company page (the lines between the companies look weird in a smaller display, so they should either be removed or the margins or padding should be adapted)
- [x] similar problem for list of conferences, the info text gets cut off on mobile
- [x] improve font size: right now the headings are huge on smaller screens, which is not super necessary. Maybe we could use a different font scale for smaller displays?

**Comment by katrin-k** [comment]
Re "lots of scrolling": hiding the sponsors on many pages seems resolved already. For those few, where the sponsors are still shown, I'd also leave them on mobile. Other lengthy content should probably wait for the complete overhaul.

**Comment by alicetragedy** [comment]
Most items have been done in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/291, now we're just waiting for the menu issue to be fixed. Hooray! 🎉

**Comment by alicetragedy** [comment]
All done. closing!!! 🎈 🎊 🎉 ✨
