### ISSUE TITLE
Add list of teams to website

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#290]
We'd love to have a list of the teams added to the website every year, similar to the list of organisers/coaches/mentors [here](http://railsgirlssummerofcode.org/about/team/). 

We already have a JSON array, containing the objects we need, which can be grabbed from the teams app (see [here](https://teams.railsgirlssummerofcode.org/students.json)), this info now "just" needs to be formatted and outputted to an html page using e.g. JavaScript like on the current `about/team` page.

I cannot evaluate the task level, as I'm not a JavaScript person 🙈 , but I believe it shouldn't be extremely difficult to accomplish. There is also a similar page (linked above) which you can base your work upon.

**Comment by katrin-k** [comment]
On which page should the students be displayed? 
Looking at the menu, a new page `students/2016 teams` seems in order, doesn't it?

**Comment by alicetragedy** [comment]
hey @katrin-k, the JSON will always return "current students", meaning it's enough to have a page `teams` or `our-teams`, as in, we don't need to necessarily give it a year in the path (of course, the page title can include the year). 

Regarding its placement within the site structure, I think it might make more sense it place it under RGSoC in the menu (aka it would be `about/our-teams`) but I'm flexible there. `students/` is more geared towards information for future students, rather than info about current ones. 
Do you have any thoughts?

**Comment by katrin-k** [comment]
You're right, placed under `about` indeed makes more sense.
