### ISSUE TITLE
Add opengraph data

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/summer-of-code#3]
Make it look prettier when sharing via social media channels

**Comment by lislis** [comment]
@carpodaster yes!
Do we have a particular image that we want associated w/ rgsoc?

**Comment by carpodaster** [comment]
@lislis I was thinking the red Railsgirls pixel heart as the default one. I will add a yaml header option that allows the specification of a different image on a per-page/per-post basis. I don't think the latter will be a  much used feature, though, but it doesn't hurt to have it, either :smile:

**Comment by lislis** [comment]
@carpodaster cool stuff, I'll see what images I can find

**Comment by alicetragedy** [comment]
@lislis have you already found one? Otherwise I have a 300dpi TIFF that's roughly 900x900px that @carpodaster could use. (made my own for the certificates since I couldn't find a hi-res one anywhere :p so I understand the problem)

**Comment by lislis** [comment]
@alicetragedy No and I haven't and that would be so cool :dancer:

**Comment by alicetragedy** [comment]
sending it by email for now, but we should probably think of the best place to store it so we don't have to keep looking for it over and over again every time we need it! :tada:

**Comment by lislis** [comment]
which is basically true for all the images.

**Comment by alicetragedy** [comment]
YES!
