### ISSUE TITLE
Teams/Students page improvements

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#301]
We finally have an overview of [current teams](http://railsgirlssummerofcode.org/about/students/) thanks to @katrin-k <3 

There's some improvements that could still be made, namely:
- sort teams by team name (some JavaScript knowledge will be needed)
- show several teams on one "row", depending on how much space is available on the display (this is a purely aesthetic improvement and needs a bit of CSS / Bootstrap knowledge)

**Comment by nbogis** [comment]
I would like to work on these enhancements

**Comment by alicetragedy** [comment]
Sounds good @nbogis! I'll assign you to this issue, and I would be very happy to answer any of your questions on things that are still unclear. Do you need anything from me, like clarifications, to get started?
For this, you will need to run jekyll locally on your computer — set up infos are in the [contributing](https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/CONTRIBUTING.md) guide, but ping me if anything doesn't work as planned. Thank you!
