### ISSUE TITLE
Sponsorship Guidelines link is 404'ing.

### ISSUE THREAD

**Issue by jimmackenzie** [rails-girls-summer-of-code/summer-of-code#32]
Hello friends!
 
I noticed that the sponsorship guidelines link is 404'ing in a few places:

1. https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/_includes/footer.html#L24
1. https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/_includes/content_sidebar.html#L10
1. https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/_layouts/default.html#L102

Looks like it should be pointing to `/sponsors/sponsor-guidelines/` from a quick glance. No time for a pull request now, but I'll circle back later. Thought I'd let you know first though :green_heart:

**Comment by alicetragedy** [comment]
hey @jimmackenzie! Thank you so much for letting us know - we will take a look and fix it asap. We've been moving some stuff around lately to get ready for the new RGSoC season, seems that we overlooked some links ;) We appreciate the feedback! :purple_heart:

**Comment by anikalindtner** [comment]
thanks for pointing out @jimmackenzie!

**Comment by sareg0** [comment]
Hey guys, 
I am hoping/thinking that this is now fixed. @jimmackenzie do let us know if you see any more things.

**Comment by jimmackenzie** [comment]
Woop! :+1: :green_heart:

**Comment by alicetragedy** [comment]
:tada:
