### ISSUE TITLE
Improve our Code of Conduct

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#331]
Even though our Code of Conduct is pretty good, I think it would be a good idea to review it and consider making changes and additions. Especially, I think we could give some examples of "unacceptable behaviour" and of micro-aggressions (because those are usually the more difficult to pinpoint). I recently came across the [18F Code of Conduct](https://github.com/18F/code-of-conduct/blob/master/code-of-conduct.md) and I especially like the section about boundaries and statements such as the following: "Impact matters more than intent. Ensuring that your behavior does not have a negative impact is your responsibility. Problems happen when we assume that our way of thinking or behaving is the norm or ok with everyone."
I think we could definitely dig through a couple of CoCs for inspiration and redefine what we really want our Code of Conduct to say.

While this isn't exactly a non-beginner task, it requires a little bit of experience with CoCs and capacity in understanding the subtleties of the language we choose to use. I'd love to pair on this with someone interested in learning more about CoCs, or I'd be happy to have a documentation-savvy person pair with someone less experienced.

**Comment by katrin-k** [comment]
The [Berlin Code of Conduct](http://berlincodeofconduct.org/) is also a good source. It goes beyond many typical phrases, too.

**Comment by alicetragedy** [comment]
@katrin-k thanks for that, it's another great CoC we can get inspired by. @Nattivolk will be working on this issue and I'm sure this is helpful!

**Comment by 1000miles** [comment]
Hey there, thanks for raising up this issue.

[co.up](http://co-up.de/code-of-conduct.html) has also a very well-thought code of conduct (that derived partly from the berlin code of conduct).

I like especially this here:
```
Communities mirror the societies in which they exist. Positive action, pushing back against discrimination, and reflecting on the harmful messages we have all internalised are essential to counteract the many forms of inequality and abuses of power that exist in society.
```

and these parts:
```
Be mindful of your surroundings and of your fellow participants. Apologise sincerely when you hurt someone. Recognise the effects of your actions are more important than your intent.
```

If that helps for inspiration, I started a collection here:
https://github.com/1000miles/coc-collections

**Comment by alicetragedy** [comment]
thanks for the comment and suggestions @1000miles 🙌
