### ISSUE TITLE
update basic info on website for 2017

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#335]
We're starting to get contacted about the next edition of RGSoC already 😱 
It would be great to update the website with information for 2017. This means:
* the date on the landing page (Jul–Sep 2017)
* the timeline (please ping me if you need exact info on this)

In the future, we might want to consider having a cleaner transition by removing some of the links to guides until we've updated them for the next edition, but I don't know if this is super necessary this year.

This task requires some basic knowledge about running jekyll, but if you have some problems getting it to work I'm happy to pair with you <3

**Comment by linberg** [comment]
I included the years on the timeline section for clarity, but it throws off the alignment on certain screen sizes. If you prefer to leave the year out, let me know and I'll send a fresh PR 👯

**Comment by alicetragedy** [comment]
closed in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/336 by @linberg ✨
