### ISSUE TITLE
Review and update the coaches guide for 2017

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#350]
Based on feedback from coaches which we received last year.

**Comment by mkalininait** [comment]
Some problems reported by the coaches of 2016:
 * [ ] I was not sure what my role as a coach would be / what were the deliverables at the end of the program
 * [ ] Wasn't sure how the program would be executed within a specific project
 * [x] Not clear how many coaches are actually necessary
 * [ ] What is the role of a remote coach that is not coaching on a day-to-day basis, but instead for project-specific things
 * [x] Wasn't clear about the benefits to be a coach
 * [x] Expected level of the students was not clear
 * [ ] Mentor's role
 * [x] Wasn't clear what to do to become a coach (based on Helpdesk)

I think that additionally to the guide we need to make a one-page pdf with really short answers on the most popular questions like the ones above.

Also, it might make sense to tell coaches a bit more about "what to expect" regarding:
 * [ ] communication with the students: possible unresponsiveness;
 * [ ] communication with the students: possible issues with the students being not co-operative ("lack of authority");
 * [ ] students' skills: coding level being different from what has been expected.

UPD: Additionally:
 * [x] Local or remote?

**Comment by mkalininait** [comment]
One more thing: how to confirm your coach status in a team. Was asked 1000 times last year.

**Comment by carpodaster** [comment]
When a coach is added to a team, they (should) get an email containing a link. Behind that link is a confirmation button

**Comment by mkalininait** [comment]
@carpodaster Yes, I actually made that note not to forget to include this in the Guide :)
Sometimes coaches don't get the email (there is no public email in their Github profile or their email address is outdated, or the email gets into spam, or whatever), and then they need to go to the team's page and press the confirmation button manually. This was not obvious to the coaches last year.

**Comment by alicetragedy** [comment]
I think there are three types of information we need to provide coaches (and other participants) with:
- information about applying/basic info about the program (found in guides on the website)
- information about using the teams app/troubleshooting (teams app help page)
- more detailed information about roles, handling communication problems, etc.. (separate guide provided to coaches of selected teams).

Information related to using the Teams app (e.g. troubleshooting) would be good to have on the teams app help page (see https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/614). We should be able to make the link to the help page more prominent if necessary. This could include screenshots and information about confirming the account.

The coach guide on the website is meant as basic information for coaches who wish to apply and find a team. I think that any very specific information about the program/the deliverables/communication tools/etc... should be provided to coaches after their team has been accepted, in the same way that we provide selected teams and selected mentors with more information before the program starts... sort of like an onboarding document. This could definitely be provided as a pdf, or as a link to a document in google docs, or any other format which we think would make sense, I don't really know what would work best there. My preferred way would be to, in the future, have all these extra documents in the teams app itself, in a personal “dashboard”.

**Comment by mkalininait** [comment]
@alicetragedy I agree with everything. 
Does this ticket cover only the basic guide on the website? 
If so, there are very few changes to be made. Many feedback issues will be covered by the onboarding guide. Btw, it seems so strange that we didn't have it before :D

**Comment by alicetragedy** [comment]
@mkalininait I feel the same way — an onboarding guide is definitely something we've always needed..
Yes, the original ticket covered the changes on the website only (as it's in our website repo). I will create a separate issue in `organization` for the onboarding guide, so I'd suggest to stick in here to the changes that we need to make on the coaches guide page on our website. thank you! 👍
