### ISSUE TITLE
broken "donate now" in sidebar

### ISSUE THREAD

**Issue by katrin-k** [rails-girls-summer-of-code/summer-of-code#39]
The "Donate now" button in the sidebar is either cut off (Safari 7.1, Chrome 37) or a line-breaker (ff 33)

![broken donate safari](https://cloud.githubusercontent.com/assets/2246045/6527813/1de9ffd0-c41e-11e4-8335-bd63e7644c3f.png)
 ![broken donate firefox](https://cloud.githubusercontent.com/assets/2246045/6527814/1e47af0e-c41e-11e4-8a49-592016e6241e.png)

**Comment by lislis** [comment]
what operating system and window size? I can't reproduce right now

**Comment by sareg0** [comment]
This is mobile view. The site is not so pretty on mobile, but we kinda shipped it without looking at mobile, so team effort :) . I took some screenshots but I figure you could take a look on mobile too @lislis

**Comment by anikalindtner** [comment]
it's also on the blog-site on chrome:

![screen shot 2015-03-06 at 22 40 26](https://cloud.githubusercontent.com/assets/1711357/6536898/d6b75368-c451-11e4-93a7-6d9fdfeb221b.png)

(and all the other sites with sidebars, i just saw)

**Comment by lislis** [comment]
AAHH, you put the button in the sidebar. I didn't even see that. I made a class with a smaller button. But you could have fixed that, too ;)  
The line break needs a little more attention, since the input has a fixed width.
