### ISSUE TITLE
Missing link to how to become an organizer on /about

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/summer-of-code#40]
http://railsgirlssummerofcode.org/about/

![screen shot 2015-03-06 at 22 44 41](https://cloud.githubusercontent.com/assets/164400/6536976/8b6fa22e-c452-11e4-97f4-9ddb7154cd82.png)

**Comment by sareg0** [comment]
wtf?! I can fix that. Okay fixed. Should be there now

**Comment by sareg0** [comment]
teh emptyness is resolved :) x

**Comment by carpodaster** [comment]
Cool! :+1: I didn't which document it should link to

**Comment by alicetragedy** [comment]
to put it in @sareg0's words.. "Awesome sauce" :sparkles:
