### ISSUE TITLE
update roles page

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#405]
The roles page is quite outdated, so it would need a nice update.
Here are the things that need changing:
- we haven't had speaker coaches for a few years, so I'd suggest to just remove the paragraph
-  replace the role “Mentor” with “Mentor / Project maintainer” in all the headings so that it's more clear
- add more examples to mentor role, e.g. that they review pull requests and help students with a roadmap at the beginning of the summer. 
- Remote coach section could be expanded a bit, something along the lines of “Remote Coaches are available for help in a central slack channel open to all students; they help participants when their team coaches aren't around or when they need specific  technical help (e.g. help figuring out an error).”
- improve wording on the sponsor paragraph, as it's quite confusing/messy. 
- improve wording on the coaching companies paragraph and remove the following line: “This role is a formalization of a very successful concept from last year: ”
- improve wording on last paragraph, for example: “If your company can’t sponsor an entire package, they can still donate a smaller amount via our crowdfunding campaign — any donation counts!”

**You're welcome to help with this issue even if you are not involved in the organisation of RGSoC or familiar with the roles**! I'd be happy to help you point you in the right direction or to review your changes.

**Comment by Benjaminpjacobs** [comment]
Hi! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by alicetragedy** [comment]
Hi @Benjaminpjacobs, it's so cool that you want to help! You're right, no one is assigned to it yet, so it's up for grabs. We'd love to have you help out with this issue! 
I've already outlined some straightforward "first steps" you can help with. Some of the other points might be more difficult to tackle if you don't know how RGSoC works, but I can be of help there, just ping me whenever you need an explanation or whenever you're stuck. Does that sound ok to you? 
Also, feel free to ask any questions you have! Welcome on board 🙌

**Comment by Benjaminpjacobs** [comment]
@alicetragedy, that sounds great. I'll get started on what is there and will absolutely reach out with questions as they arise. Thank you!

**Comment by Benjaminpjacobs** [comment]
@alicetragedy I've submitted a pr addressing the basic aspects of those issue but I'm more than open to any feedback or if you need anything else based on those changes. Just let me know! I'm happy to help where I can.

**Comment by Benjaminpjacobs** [comment]
@alicetragedy thank you for your feedback! I've updated the PR based on your comments. Please let me know if there is anything else you need on this one.

**Comment by alicetragedy** [comment]
Closed in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/419 🎉
