### ISSUE TITLE
Duplicate: /landing.html vs. /index.html

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/summer-of-code#41]
While working on 7141bb46d315334d64d85ca1818c39de7a105dab I noticed that the front page is served by `landing.html`, not `index.html` (I couldn't figure out why my changes in index.html wouldn't show after I rebuild my local jekyll site).

I don't know enough jekyll-foo to understand how landing gets aliased to index, but I do think that we should either merge the files, rename them or delete the one that's obsolete. It's a bit confusing as it is now. Halp needed :smile:

**Comment by lislis** [comment]
You're right, closed by 7961378025afc7299635eaa7bed4a93c02b8095b
