### ISSUE TITLE
Add missing organisers to team page

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#474]
@acnagy and @inescoelho are missing as organisers from the [Team](https://railsgirlssummerofcode.org/about/team/) page. :)

**Comment by carpodaster** [comment]
@acnagy do you have an account on the teams app? I can't seem to find you by your GH handle or otherwise.

**Comment by carpodaster** [comment]
@inescoelho is showing up as organizer now. I changed the role linked to the team "13th floor" (2016) to "supervisor" (it was "organizer") – is that correct? If not, feel free to change back, but I added the required  team-unbound "organizer" role.

**Comment by alicetragedy** [comment]
Thank you so much @carpodaster! I'm not sure about the “13th floor” team, I don't think we had a team with that name participating that year, so not sure why @inescoelho was attached to it. Let's see what she says, but I think we can just leave it like it is :)

**Comment by inescoelho** [comment]
Hi @carpodaster and @alicetragedy! I have no idea why I'm attached to that team, it doesn't even seem to be a participating team :see_no_evil:

**Comment by acnagy** [comment]
@carpodaster that's weird! I did during the selection process... - it'd be under this handle, or I guess anything that's attached to my personal email? That said, if I need to sign up again, lemme know - I can certainly do that.

**Comment by carpodaster** [comment]
@acnagy There is no user by your GH handle 😢  Can you log in again on https://teams.railsgirlssummerofcode.org? It will (should) create a new account.

**Comment by carpodaster** [comment]
@inescoelho Weird. 😕  In any event, I removed you from that phantom team 👻

**Comment by acnagy** [comment]
@carpodaster done 🤘 I'm all set up!

**Comment by carpodaster** [comment]
Aaaaand finally listed on https://railsgirlssummerofcode.org/about/team/ 😄

**Comment by alicetragedy** [comment]
Yessss, awesome! 🙌 Thank you @carpodaster for taking care of this issue and @acnagy for setting up an account again to facilitate that. ❤️ 
So happy to see this issue closed 😂 🙈
