### ISSUE TITLE
current page navigation arrow missing

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#48]
The arrow in the sidebar for the current / active page has disappeared.
@lislis Is this a feature or a bug? :p

![screen shot 2015-03-10 at 20 11 27](https://cloud.githubusercontent.com/assets/3143348/6583049/c2bdae58-c761-11e4-843a-9e2e0208ac98.png)

**Comment by anikalindtner** [comment]
it's a feature :)

**Comment by alicetragedy** [comment]
ok, so I'll close this ;)
