### ISSUE TITLE
Add an archive

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/summer-of-code#5]

**Comment by lislis** [comment]
There is a gem for that https://github.com/jekyll/jekyll-archives

**Comment by lislis** [comment]
So, I probably go for a simple archive like template and a link like `/blog/archive/`. I hope I can get it done tonight.

**Comment by anikalindtner** [comment]
GO FOR IT!

**Comment by lislis** [comment]
So, the archive would look this
![screen shot 2015-02-13 at 00 13 28](https://cloud.githubusercontent.com/assets/1006478/6179078/d49399f4-b315-11e4-89c2-eea555adbd58.png)

**Comment by carpodaster** [comment]
That looks great, @lislis ! :shipit: !

**Comment by anikalindtner** [comment]
<3!!!

**Comment by alicetragedy** [comment]
Looking good! :heart:

**Comment by lislis** [comment]
Here we go http://railsgirlssummerofcode.org/blog/archive/

**Comment by alicetragedy** [comment]
YAY!

**Comment by carpodaster** [comment]
That is so cool, thanks @lislis !
