### ISSUE TITLE
Edit documentation

### ISSUE THREAD

**Issue by ljl7123** [rails-girls-summer-of-code/summer-of-code#507]
My university technical writing course has an assignment which involves editing documentation on GitHub repositories as practice in real world settings. Edits may involve aspects like style, structure, and concision. Existing style guidelines would be taken into account. The following is one of the resources I would be using:

https://jacobian.org/writing/technical-style/ 

Would anyone mind if I propose edits to documentation in this repository? It would really help me out!

**Comment by alicetragedy** [comment]
hej @ljl7123 — sorry to have taken so long to get back to you! 
We'd love to have you contribute and suggest some edits to the current documentation — PRs are welcome! 🙌 
We currently have [this open PR](https://github.com/rails-girls-summer-of-code/summer-of-code/pull/483) which I'm hoping to merge soon and might conflict slightly with your work — it adds some edits to the readme, but hopefully by the time you see this message the changes will have been incorporated already. 

Please let me know if you have any questions or if there's anything you're unsure about. I'm always happy to help! ✨

**Comment by alicetragedy** [comment]
Hi @ljl7123, I'm going to close this issue for now since it's been opened for a while and the description is a little vague. Please don't hesitate to open a new one if this is something you want to tackle in the future. I'd be happy to talk through some of the things that need changing!
