### ISSUE TITLE
Add conferences logos to the footer and conferences page

### ISSUE THREAD

**Issue by anasofiapinho** [rails-girls-summer-of-code/summer-of-code#538]
One of the benefits of conferences giving us tickets is that we add their logos and info to our footer and the conferences page in our website.

The status, info and logos are on the Conferences 2018 spreadsheet.

**Comment by anasofiapinho** [comment]
Conferences are not sending their logos, even when requested multiple times. I can tray to save them from their websites.

I think that the info we got from the conferences are ok though.

**Comment by anasofiapinho** [comment]
Following our weekly call, I assigned this issue to Ramón as he is working on the Conference List issue https://github.com/rails-girls-summer-of-code/summer-of-code/issues/470.

The conferences logos are on the drive, in the Conferences folder, however, ODD EU replied to my email with a new logo, but they didn't send it. If they send the new logo, I'll let you know. If you need more help from me, just mention me or send me a message on Slack.

**Comment by alicetragedy** [comment]
done in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/557. closing!
