### ISSUE TITLE
Create blog post for the 2018 Wrap Up Events

### ISSUE THREAD

**Issue by anasofiapinho** [rails-girls-summer-of-code/summer-of-code#545]
Let's start organising the wrap up events!

**Comment by anasofiapinho** [comment]
@nerdyvaishali Can we film this week's supervisors calls? I need like 10 seconds. We don't need any sound recording, and people can just wave.

**Comment by anasofiapinho** [comment]
Copy and image done. You can check the PR here:
https://github.com/rails-girls-summer-of-code/summer-of-code/pull/552

**Comment by alicetragedy** [comment]
Not sure if it helps @anasofiapinho but I have just created an issue for the Berlin event, you can find it here: https://github.com/rails-girls-summer-of-code/announcements/issues/23 feel free to add a link to the blog post and make public announcements already! 🙌

**Comment by anasofiapinho** [comment]
As the blog post was already published last week (see [link](https://railsgirlssummerofcode.org/blog/2018-09-19-wrap-up-rgsoc-2018)), I have added a section about the Berlin's event below. 

@alicetragedy, if you want to take a look at the PR, it's [here](https://github.com/rails-girls-summer-of-code/summer-of-code/pull/554). If I had ThoughtWorks's office picture, I would add it below the "Berlin Event" title.

If you're ok with it, I can reuse this image to announce the Berlin event on social media. I would link the publications to the blog post as well.

![rgsoc-2018-wrap-up-event-berlin](https://user-images.githubusercontent.com/3285560/45948388-a9b37700-bfef-11e8-9c1a-85c495b017c2.png)

**Comment by anasofiapinho** [comment]
This is done!
