### ISSUE TITLE
small css refactor for conferences page

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#574]
As was discussed in [this PR](https://github.com/rails-girls-summer-of-code/summer-of-code/pull/557#pullrequestreview-174923535), we‘d like to move the small css snippet that styles images on the conferences page (`.conferences-container img`) from the `style.scss` file into the `layout.scss`. 

This task is a fairly straight-forward one, and could be appropriate as a ✨first-time contribution ✨. Don't hesitate to comment if you're interested in picking this up or if you have any questions!

**Comment by CleverFool77** [comment]
I would like to take this issue.

**Comment by azkarmoulana** [comment]
@alicetragedy  I'll take this

**Comment by alicetragedy** [comment]
hey @azkarmoulana, that's great! All the info you need should be above, but if you need any help just ping me in this issue. ✨

**Comment by alicetragedy** [comment]
closed in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/588.
