### ISSUE TITLE
mobile improvements

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#65]
So I took a look at the site on a tablet, and here are a few things we could still improve.

These are all minor things, but worth fixing eventually.

![image-2](https://cloud.githubusercontent.com/assets/3143348/6963492/5100f1d0-d940-11e4-93ef-9d5b070351ed.jpg)
- The burger menu has no margin or padding at the top, it makes it look very weird. 
- The progress bar needs fixing on mobile, as it doesn't show all icons.

![image-1](https://cloud.githubusercontent.com/assets/3143348/6963528/a70c3684-d940-11e4-81ba-90e32c108975.jpg)
- When the sponsor packages are stacked, there is no space between the top and the bottom one.

![image](https://cloud.githubusercontent.com/assets/3143348/6963540/c3f3ce56-d940-11e4-84ed-ecfb19b60bcc.jpg)

+ [ ] The donate button is way bigger than necessary in the page views. This is from the application guide, it comes from the sidebar and could probably also be hidden.
+ [ ] Not sure if we need all the sidebar links at the bottom of each page; in theory we can access everything through the top menu.
+ [ ] Which brings me to the next point: why not make a sticky menu at the top? It's not so bad on tablet, but on a mobile phone you have to do A LOT of scrolling if you have to get back up and navigate to another page.

**Comment by anikalindtner** [comment]
pinging @lislis here <3

**Comment by lislis** [comment]
on it
