### ISSUE TITLE
CORS issue on /about/team

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/summer-of-code#67]
http://railsgirlssummerofcode.org/about/team/ doesn't load anymore:

> That didn't work. Maybe a CORS thing?
> – team.js:25

**Comment by marcgreenstock** [comment]
Yeah, CORS issue. Seems to be sporadic on Chrome, possibly due to the force SSL redirect 307 redirect the teams app does and the headers not being sent with this.

Firefox is going to have some trouble because the protocol doesn't match, i.e. http vs https.

To fix we could just turn off force SSL for `ContributorsController#index`

**Comment by carpodaster** [comment]
Isn't there a HTTP header we can send? I'm not very familiar with CORS but I remember something like that. I shall look it up.

**Comment by marcgreenstock** [comment]
It's already being sent: https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/app/controllers/contributors_controller.rb#L2.

**Comment by carpodaster** [comment]
Ah, gotcha. Maybe just change the protocol to SSL in https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/assets/javascripts/team.js#L9 ?

![](http://tn.en.fishki.net/26/upload/en/201305/19/10633/7bb1b10ba129b6fc7d14a4de222a209f.jpg)

**Comment by marcgreenstock** [comment]
I'm looking for a way to disable force_ssl only on `ContributorsController#index` which should help solve the issue of the redirect getting in the way. Another thing to try would be changing the url to `https://teams.railsgirlssummerofcode.org/contributors.json` in the JS code.

**Comment by marcgreenstock** [comment]
yes, didn't realise this was a gh-pages thing, yeah, change it there, it can't make it any worse.

**Comment by carpodaster** [comment]
Voilá! Done. :smile: Cool beans! :green_heart:

**Comment by marcgreenstock** [comment]
Nice.
