### ISSUE TITLE
Protect our visitors' privacy with 2-click social buttons

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/summer-of-code#7]
https://github.com/heiseonline/shariff

**Comment by lislis** [comment]
Hey @carpodaster can I take over here or are you already working on it?

**Comment by carpodaster** [comment]
@lislis Go ahead, I haven't worked on it yet

**Comment by lislis** [comment]
coooooool

**Comment by lislis** [comment]
Now live!

**Comment by alicetragedy** [comment]
:tada:

**Comment by alicetragedy** [comment]
When I read that gem's name I always have to think of this guy.. http://en.wikipedia.org/wiki/Omar_Sharif :movie_camera:
