### ISSUE TITLE
Rework font 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code#73]
Our font is a bit small and that's why @apertoclaudi, @alexwllms and I have decided to rebrand everything to PAPYRUS! .... (BÄM!)

hahaha, no, but actually resizing it might be a first good step to make it more readable, especially for our blog (now that we have so amazing blog posts with @alicetragedy and @sareg0 writing ALL THE THINGS <3 )

**Comment by ApertoClaudi** [comment]
I made a screenshot, so that all of you can imagine how it will look like: 
![rgsoc-papyrus](https://cloud.githubusercontent.com/assets/7582849/7535613/4b29d76e-f587-11e4-86f8-3d304216da8d.png)

**Comment by ApertoClaudi** [comment]
… just kidding. 
Here is a screenshot how the blog will look like with a typochange from 16 to 18 pixel:

![bildschirmfoto 2015-05-08 um 12 43 18](https://cloud.githubusercontent.com/assets/7582849/7535660/b5cc7054-f587-11e4-88d2-3e51e702a7ee.png)

**Comment by anikalindtner** [comment]
hahahaha! AWESOME! LOVE IT! DO EET! SHIP IT!

**Comment by alicetragedy** [comment]
iirc this has already been implemented – can we close the issue now? :) @anikalindtner @ApertoClaudi

**Comment by alicetragedy** [comment]
We've now changed the font to 18px as main body size everywhere across the site.
I've noticed that bold and italic don't show so well though (probably missing styles), we might have to add those styles to the font so it shows properly. I will take care of that so we finally have proper bold and italic styles that don't look crappy! <3

**Comment by alicetragedy** [comment]
bold and italic finally fixed in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/170. :tada:

**Comment by alicetragedy** [comment]
![before-after](https://cloud.githubusercontent.com/assets/3143348/11499149/2e48c69c-9824-11e5-83ef-55e7620af748.jpg)

makes a nice difference especially on the italics. 
I think we can close this!

**Comment by anikalindtner** [comment]
:tada:
