### ISSUE TITLE
cors issues in firefox

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/summer-of-code#75]
http://campaign.railsgirlssummerofcode.org/donations/stats.json and http://campaign.railsgirlssummerofcode.org/donations.json are causing problems in Firefox 37

**Comment by sareg0** [comment]
oh, is this something you can fix yourself. Is it just the progress bar that is causing a problem?

**Comment by alicetragedy** [comment]
@lislis is this still a thing?

**Comment by alicetragedy** [comment]
@lislis I'd like to close this if it isn't an issue anymore. anything I can do to check? :)

**Comment by lislis** [comment]
Seems to be fine now :)

**Comment by alicetragedy** [comment]
:tada:
