### ISSUE TITLE
RSVP for Kickoff Party @DaWanda

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code#84]
Date: Friday, July 3rd 2015. 
Where: DaWanda office, Windscheidstr. 18  10627 Berlin 
When: starting at 7pm 
What: BBQ

Please write a comment if you are joining! <3

**Comment by anikalindtner** [comment]
I'm in.

**Comment by alicetragedy** [comment]
I'll be there as well! :heart:

**Comment by lucaspinto** [comment]
:raising_hand:

**Comment by lislis** [comment]
:raising_hand:

**Comment by sareg0** [comment]
I will be there with bells on :) with a +1

**Comment by berlintam** [comment]
woot!

**Comment by carpodaster** [comment]
:raising_hand:

**Comment by ApertoClaudi** [comment]
I'll be there! :tada:

**Comment by katrin-k** [comment]
:raising_hand:

**Comment by 1000miles** [comment]
:raising_hand: Thaaaank you!

**Comment by alexwllms** [comment]
Pretty sure I'll be there :P

**Comment by Realtin** [comment]
I'm in + 1! :)

**Comment by sxosxo** [comment]
See you there.

**Comment by raluka** [comment]
I'll be there, thanks for invite!

**Comment by siemieniec** [comment]
Me too! :raising_hand:

**Comment by eljojo** [comment]
we're going with @malwine :dancers:

**Comment by hagenburger** [comment]
I’ll be there! :)

**Comment by anomiseditrix** [comment]
see you there!

**Comment by lauralindal** [comment]
me too!

**Comment by starkcoffee** [comment]
yes please!

**Comment by finnp** [comment]
:raising_hand:

**Comment by ghost** [comment]
we are in!

**Comment by nynnejc** [comment]
Will be there!

**Comment by sareg0** [comment]
we @rubyherzelein can you specify how many people from your group will be coming (is that for just the two students, or all the coaches and such too?)

**Comment by nynnejc** [comment]
I know that I'll be there as well as Franzi & Tam. Erik can't make it, and I'll ask Duana if she can come.

**Comment by janl** [comment]
Count me in!

**Comment by ellenkoenig** [comment]
Would be happy to join!

**Comment by ferbsx** [comment]
🙋 I'm in 😄

**Comment by bioshrimp** [comment]
yes, please. :ghost:

**Comment by juliusv** [comment]
I'm in!

**Comment by johnjohndoe** [comment]
+1

**Comment by alhewpl** [comment]
I'm in :) +1

**Comment by BenStW** [comment]
happy to join!

**Comment by kaeptnjules** [comment]
I`m in too. :)

**Comment by atroyn** [comment]
Will be there!

**Comment by plexus** [comment]
We're joining with a delegation from @ticketsolve. Eight people in total including @bjoska, @shanly, @smiroddi and myself.

**Comment by anikalindtner** [comment]
\o/ whohoo! so cool!

**Comment by ghost** [comment]
I can't join in the evening :-(

**Comment by plexus** [comment]
Ok I guess we're seven then :)

**Comment by sarahkami** [comment]
I'll happily join :)

**Comment by madziaf** [comment]
I'll be there!

**Comment by svenfuchs** [comment]
+1

**Comment by arianepaola** [comment]
+1 and guest :)

**Comment by ariaru** [comment]
Me, too!

**Comment by neonichu** [comment]
+1

**Comment by asaaki** [comment]
I'll try to make it.

**Comment by BriocheBerlin** [comment]
I'll be there :)

**Comment by jbspeakr** [comment]
In +2 ;D

**Comment by bl00dymarie** [comment]
I am happy to join, too

**Comment by frimelle** [comment]
I'll be there!

**Comment by musagetin** [comment]
+1 =)

**Comment by lucaong** [comment]
I'm in!

**Comment by biancavlz** [comment]
:raising_hand:

**Comment by cmw** [comment]
:hand:

**Comment by Lelith** [comment]
o/ also in

**Comment by markauskas** [comment]
oh yes!

**Comment by starkcoffee** [comment]
Damn I can't make it anymore :(:(

**Comment by anikalindtner** [comment]
@starkcoffee oh nooooes! :'(

**Comment by langjoh** [comment]
I'll be there!

**Comment by laushinka** [comment]
I'll be there! Possibly with plus one.

**Comment by drogus** [comment]
I'll be there as well (if it's not too late to confirm ;) )

**Comment by anikalindtner** [comment]
@drogus it's not! WHEEEEE \o/

**Comment by juliusv** [comment]
Eek, gonna bring one or two more people - still ok? They might go hungry, that's ok :)

**Comment by schultyy** [comment]
Late but I'll join as well

**Comment by tyranja** [comment]
Me too, +1

**Comment by sareg0** [comment]
that should be fine @tyranja and @schultyy

**Comment by sareg0** [comment]
Closing this puppy up now! Thank you everyone who made it!! It was a blast, and of course thanks once again to the amazing @lauralindal  and the entire DaWanda crew for hosting us. <3 <3

Anyone with any great photos from the event, please do send them through to summer-of-code@railsgirls.com

We'd love to showcase them on the Rails Girls Summer of Code blog

xxx
