### ISSUE TITLE
fix sidebar in single blog post view

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#88]
For some reason the sidebar has moved to the bottom in the single page view. :(

![screen shot 2015-06-15 at 21 26 07](https://cloud.githubusercontent.com/assets/3143348/8168761/83329f38-13a5-11e5-9cb0-75ccb2911e32.png)

**Comment by sareg0** [comment]
done and done! fixed with Pull Request #89
